#nginx-pod.yaml
#"kubectl create -f nginx-pod.yaml" to create pod.
#"kubectl get pod" to list pods
#"kubectl get pod -o wide" to list pods with wide details.
#"kubectl get pod nginx -o wide" to list specific pod with details.
#"kubectl get pod -l app=nginx"  to list pod with label tag.
#"kubectl describe pod nginx" to describe specific pod.
#"kubectl exec -it nginx -- /bin/sh" to run command into container.
#"kubectl delete -f nginx-pod.yaml" to delete pod.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    tier: dev
spec:
  containers:
  - name: nginx-container
    image: nginx
